#cloud-config

package_update: true
package_upgrade: true

packages:
  - curl
  - git
  - jq
  - ca-certificates
  - libicu-dev
  - libssl-dev

write_files:
  - path: /opt/bootstrap.sh
    permissions: "0755"
    content: |
      #!/bin/bash
      set -euo pipefail

      echo "Starting bootstrap..."

      RUNNER_DIR=/runner
      mkdir -p $RUNNER_DIR
      cd $RUNNER_DIR

      ARCH=$(uname -m)

      if [[ "$ARCH" == "aarch64" ]]; then
        RUNNER_ARCH="arm64"
      else
        RUNNER_ARCH="x64"
      fi

      echo "Detected arch: $RUNNER_ARCH"

      curl -L -o runner.tar.gz \
        https://github.com/actions/runner/releases/latest/download/actions-runner-linux-${RUNNER_ARCH}.tar.gz

      tar xzf runner.tar.gz

      echo "Configuring runner..."

      ./config.sh \
        --url https://github.com/Tajana22/abbot \
        --token ${RUNNER_TOKEN} \
        --unattended \
        --replace \
        --ephemeral \
        --labels ephemeral,hetzner

      echo "Starting runner..."

      ./run.sh

runcmd:
  - /opt/bootstrap.sh
